
String[] questions ={"What do you call a hippie’s wife?", "What do you call a cow with two legs?", "What do you call a dangerous sun shower?"};
String[] answers ={"A Mississippi!", "Lean Beef!", "A rain of terror!"};
String[] screenName ={"dumbest_man_alive", "loliateyourcat", "iamyourdaddy", "buh-buh-bacon"};
int index = int(random(screenName.length));
void setup() {
println("Welcome user I");
delay(2000);
println("to my little stupid joke room");
delay(2000);
println("Now, before we start, let's get you a new identity");
delay(2000);
println("like a screen name!");
delay(2000);
println("I'll give you 5 second to decide what it is");
delay(2000);
println("and when you're done, just shout it out");
delay(2000);
println("5");
delay(1000);
println("4");
delay(1000);
println("3");
delay(1000);
println("2");
delay(1000);
println("1");
delay(1000);
println("Alright, time's up!");
delay(2000);
println("Hmmm, I don't like that name");
delay(2000);
println("Got it! I'll call you " +screenName[index]);
delay(2000);
println("Let's begin, shall we");
delay(4000);
println("Do you want to hear a bad joke?");
delay(2000);
println("Here we go");
delay(4000);
println(questions[0]);
delay(5000);
println(answers[0]);
delay(3000);
println("Got you?");
delay(3000);
println("No?");
delay(3000);
println("Let's try this again");
delay(4000);
println(questions[1]);
delay(5000);
println(answers[1]);
delay(3000);
println("Still not satisfied?");
delay(3000);
println("Fine, last joke");
delay(3000);
println(questions[2]);
delay(4000);
println(answers[2]);
delay(3000);
println("Hmm... you are very hard to please aren't you?");
delay(3000);
println("Alright, bonus quesion"); 
delay(10000);
println("Just kidding");
delay(3000);
println("I don't have one");
delay(3000);
println("bye");

}
